# docker-compose build
version: '2.1'
volumes:
  dbbackups:
  postgis-data: 
services:
  db:
    build: .
    environment:
      # If you need to create multiple database yo u can add coma separated databases eg gis,data
      - POSTGRES_DB=jehlomat
      - POSTGRES_USER=jehlomat
      - POSTGRES_PASS=jehlomat
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - ./service-jehlomat:/service-jehlomat
    healthcheck:
      test: "exit 0"