import { SyringeReadModel } from './types/SyringeReadModel';

export const mock: SyringeReadModel = {
    syringeList: [
        {
            id: 'R4YFD1AC',
            createdAt: 1637092279,
            createdBy: {
                id: 0,
                email: 'peter@raavn.net',
                username: 'Peter124',
                verified: false,
                organizationId: 1,
                teamId: 1,
                isAdmin: true,
            },
            reservedTill: 1637092279,
            reservedBy: {
                id: 0,
                email: 'peter@raavn.net',
                username: 'Peter124',
                verified: false,
                organizationId: 1,
                teamId: 1,
                isAdmin: true,
            },
            gps_coordinates: '49.22326399194605, 16.59743398061707',
            demolished: false,
            demolishedAt: 1639092279,
            demolishedBy: {
                id: 0,
                email: 'peter@raavn.net',
                username: 'Peter123',
                verified: false,
                organizationId: 0,
                teamId: 0,
                isAdmin: true,
            },
            count: 1,
            note: 'note 1',
            demolisher: 'NO',
            location: {
                id: 0,
                okres: 'CZ0323',
                obec: 554791,
                mestkaCast: 546003,
            },
        },
        {
            id: 'DMGID1AC',
            createdAt: 1637092279,
            createdBy: {
                id: 0,
                email: 'peter@raavn.net',
                username: 'Peter124',
                verified: false,
                organizationId: 1,
                teamId: 1,
                isAdmin: true,
            },
            reservedTill: 1637092279,
            reservedBy: {
                id: 0,
                email: 'peter@raavn.net',
                username: 'Peter124',
                verified: false,
                organizationId: 1,
                teamId: 1,
                isAdmin: true,
            },
            gps_coordinates: '49.199025530527344, 16.606748383444558',
            demolished: true,
            demolishedAt: 1639092279,
            demolishedBy: {
                id: 0,
                email: 'peter@raavn.net',
                username: 'Peter123',
                verified: false,
                organizationId: 0,
                teamId: 0,
                isAdmin: true,
            },
            count: 1,
            note: 'note 1',
            demolisher: 'NO',
            location: {
                id: 0,
                okres: 'CZ0323',
                obec: 554791,
                mestkaCast: 546003,
            },
        },
        {
            id: 'R4YFD1F2',
            createdAt: 1637092279,
            createdBy: {
                id: 0,
                email: 'peter@raavn.net',
                username: 'Peter124',
                verified: false,
                organizationId: 1,
                teamId: 1,
                isAdmin: true,
            },
            gps_coordinates: '49.204466102894855, 16.573198482117157',
            demolished: false,
            count: 1,
            note: 'note 1',
            demolisher: 'NO',
            location: {
                id: 0,
                okres: 'CZ0323',
                obec: 554791,
                mestkaCast: 546003,
            },
        },
    ],
    pageInfo: {
        index: 0,
        size: 20,
        hasMore: false,
    },
};
