export const texts = {
    TITLE: 'Nové heslo',
    MOBILE_TITLE: 'Nové heslo',
    INPUT__PASS__LABEL: 'Nové heslo',
    INPUT__PASS__PLACEHOLDER: 'Snadno zapomatovatelné, těžce uhodnutelné',
    INPUT__RE_PASS__LABEL: 'Kontrola hesla',
    INPUT__RE_PASS__PLACEHOLDER: 'Zadejte stejné heslo',
    VALIDATIONS__REQUIRED: 'Povinná položka',
    VALIDATIONS__SYMBOLS: 'Heslo musí obsahovat číslo, velké a malé písmeno',
    VALIDATIONS__MIN_LENGTH: 'Heslo musí být 8 znaků dlouhé',
    VALIDATIONS__MATCH: 'Hesla musí být stejná',
    BUTTONS__SEND: 'Nastav heslo',
    MODAL__MISSING_PARAMETERS__TEXT: 'V URL adresa chybí potřebné parametry pro provedení reset hesla. Prosím ověřte, že jste zkopíroval/a celý link pro reset hesla do prohlížeče.',
    MODAL__UNABLE_VERIFY__TEXT: 'Token pro reset hesla není platný. Jeho platnost již vypršela, nebo nebyl správně zkopirovaný do prohlížeče.',
};
