export const LINKS = {
  home: "/",
  login: "/login",
  about: "/about",
  user: "/uzivatel",
  userNew: "/uzivatel/novy",
  userValidation: "/uzivatel/validace",
  userRegistration: "/uzivatel/registrace",
  userEdit: "/uzivatel/upravit",
  userThankYou: "/uzivatel/dekujeme",
  organization: "/organizace",
  organizationRegistration: "/organizace/registrace",
  organizationThankYou: "/organizace/dekujeme",
  profile: "/profil",
  newFind: (step?: 0 | 1 | 2 | 3 | 4) =>
    `/novy-nalez${step ? `?step=${step}` : ""}`,
  findings: "/nalezy",
  error: "/error",
  trackingFind: "/trackovani-nalezu",
  disposalInstructions: "/navod-likvidace",
  policeAssistance: "/ohlasit-nalez-policii",
} as const
