name: 'Terraform Apply on push'
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/aws/**'
env:
  tf_version: '0.15.4'
  tf_working_dir: 'infrastructure/aws'
  TF_VAR_development-domain-certificate-arn: ${{ secrets.DEVELOPMENT_DOMAIN_CERTIFICATE_ARN }}
  TF_VAR_development-public-domain: ${{ secrets.DEVELOPMENT_PUBLIC_DOMAIN }}
  TF_VAR_development-frontend-bucket-name: ${{ secrets.DEVELOPMENT_FRONTEND_BUCKET_NAME }}
  TF_VAR_database-username: ${{ secrets.DATABASE_USERNAME }}
  TF_VAR_database-password: ${{ secrets.DATABASE_PASSWORD }}
  TF_VAR_super-admin-email: ${{ secrets.SUPER_ADMIN_EMAIL }}
  TF_VAR_jwt-issuer: ${{ secrets.JWT_ISSUER }}
  TF_VAR_jwt-audience: ${{ secrets.JWT_AUDIENCE }}
  TF_VAR_jwt-realm: ${{ secrets.JWT_REALM }}
  TF_VAR_mailjet-public-key: ${{ secrets.MAILJET_PUBLIC_KEY }}
  TF_VAR_mailjet-private-key: ${{ secrets.MAILJET_PRIVATE_KEY }}
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

