name: 'Test FE pull requests'

on:
  pull_request:
    branches:
      - master
    paths:
      - 'web-jehlomat/**'
env:
  name: 'web-jehlomat'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Build'
        run: |
          npm ci
          npm run build
        working-directory: ${{ env.name }}
